### 1. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
t = torch.rand(size = (7,7))

### 2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)`

In [ ]:
# Create another random tensor
t2 = torch.rand(size = (1,7))

# Perform matrix multiplication
torch.matmul(t, t2.T)

tensor([[1.3401],
        [0.5705],
        [0.3871],
        [0.4502],
        [0.7183],
        [0.9546],
        [1.1526]])

### 3. Set the random seed to `0` and do 1 & 2 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
torch.manual_seed(0)

# Create two random tensors
t3 = torch.rand(size = (7,7))
t4 = torch.rand(size = (1,7))
# Matrix multiply tensors
torch.matmul(t3, t4.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 4. Set random seet on GPU

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(42)


### 5. Workng with GPU

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
t5 = torch.rand(size = (2,3), device = 'cuda')
t6 = torch.rand(size = (2,3), device = 'cuda')


### 6. Perform a matrix multiplication on the GPU

In [ ]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(t5, t6.T)
result

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 7. Find the maximum and minimum values of tensor

In [ ]:
# Find max
print(result.max())
# Find min
print(result.min())

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 8. Find the maximum and minimum index values

In [ ]:
# Find arg max
print(result.argmax())

# Find arg min
print(result.argmin())

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 9. Squeezing and unsqueezing

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t_final = torch.rand(size = (1, 1, 1, 10))

# Remove single dimensions
t_final_removed = torch.squeeze(t_final)

# Print out tensors and their shapes
print(f'Before squeezing: {t_final} of shape {t_final.shape}')
print()
print(f'After squeezing: {t_final_removed} of shape {t_final_removed.shape}')

Before squeezing: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) of shape torch.Size([1, 1, 1, 10])

After squeezing: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) of shape torch.Size([10])
